services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cluster_name
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE keyspaces'"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    volumes:
      - ./Backend:/app

